[build]
builder = "DOCKERFILE"
buildCommand = "apt-get update && apt-get install -y chromium-browser chromium-chromedriver"

[deploy]
startCommand = "gunicorn api:app --bind 0.0.0.0:${PORT:-5000} --timeout 180 --workers 2"
healthcheckPath = "/health"
healthcheckTimeout = 180
restartPolicyType = "always"

[deploy.worker]
command = "gunicorn api:app"
count = 2

[deploy.resources]
memory = 512
cpu = 1

[deploy.env]
PYTHONUNBUFFERED = "1"
