[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300

[[services]]
name = "web"
protocol = "http"
internal_port = 8080

[services.restart_policy]
condition = "on-failure"
max_retries = 3

[services.concurrency]
type = "connections"
hard_limit = 25
soft_limit = 20
