# railway.toml
[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt && playwright install chromium --with-deps"

[deploy]
startCommand = "gunicorn app:app --timeout 120 --workers 2 --threads 4"
healthcheckPath = "/health"
healthcheckTimeout = 300

[[services]]
name = "web"
protocol = "http"
internal_port = 8080

[services.restart_policy]
condition = "on-failure"
max_retries = 3

[services.concurrency]
type = "connections"
hard_limit = 25
soft_limit = 20
