[build]
builder = "nixpacks"
buildCommand = """
apt-get update && \
apt-get install -y python3-dev build-essential && \
pip install --no-cache-dir -r requirements.txt && \
playwright install chromium && \
playwright install-deps
"""

[deploy]
startCommand = "gunicorn api:app --workers 2 --timeout 180 --graceful-timeout 120 --max-requests 1000 --max-requests-jitter 50"
healthcheckPath = "/health"
healthcheckTimeout = 180
restartPolicy = "always"

[deploy.resources]
memory = 1024
cpu = 1

[deploy.env]
PYTHONUNBUFFERED = "1"
PLAYWRIGHT_BROWSERS_PATH = "0"
