[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt && playwright install chromium && playwright install-deps"

[deploy]
startCommand = "gunicorn api:app --worker-class gevent --workers 2 --timeout 180 --graceful-timeout 120 --max-requests 1000 --max-requests-jitter 50"
healthcheckPath = "/health"
healthcheckTimeout = 180
restartPolicy = "always"

[deploy.resources]
memory = 1024
cpu = 1

[deploy.env]
PYTHONUNBUFFERED = "1"
PLAYWRIGHT_BROWSERS_PATH = "0"
