# railway.toml
[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt && playwright install chromium --with-deps"

[deploy]
startCommand = "gunicorn app:app --timeout 120 --workers 2 --threads 4"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3

[[services]]
name = "web"
protocol = "http"
internal_port = 8080
processes = ["app"]

[services.concurrency]
type = "connections"
hard_limit = 25
soft_limit = 20
