[build]
builder = "nixpacks"
buildCommand = "apt-get update && apt-get install -y chromium-browser chromium-chromedriver"

[deploy]
startCommand = "gunicorn api:app"
healthcheckPath = "/health"
healthcheckTimeout = 180
restartPolicyType = "always"

[deploy.worker]
command = "gunicorn api:app"
count = 2

[deploy.resources]
memory = 512
cpu = 1

[deploy.env]
PYTHONUNBUFFERED = "1"
