[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "gunicorn --preload api:app --bind 0.0.0.0:$PORT --timeout 180 --workers 1"
healthcheckPath = "/health"
healthcheckTimeout = 180
restartPolicyType = "always"

[deploy.worker]
command = "gunicorn api:app"
count = 2

[deploy.resources]
memory = 512
cpu = 1

[deploy.env]
PYTHONUNBUFFERED = "1"
